name: esbuild-publish

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      nodeVersion:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build bundle
        run: npm run build

      - name: Publish bundle
        run: npm run publish-bundle
