name: npm-publish

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      nodeVersion:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: List files
        run: ls -la

      - name: Display package.json
        run: cat package.json

      - name: Display current directory
        run: pwd

      - name: Build
        run: npm run build

      - name: Determine npm dist-tag
        id: distTag
        run: |
          # Extract version from package.json
          VERSION=$(node -p "require('./package.json').version")
          echo "Version: $VERSION"

          # Check if version contains prerelease identifiers
          if [[ "$VERSION" =~ -([a-zA-Z]+) ]]; then
            DIST_TAG="${BASH_REMATCH[1]}"
            echo "Detected prerelease tag: $DIST_TAG"
            echo "tag=$DIST_TAG" >> $GITHUB_OUTPUT
          else
            echo "Detected stable release, using 'latest' tag"
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        run: npm publish --access public --tag ${{ steps.distTag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
