name: npm-publish

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      nodeVersion:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: List files
        run: ls -la

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish
