name: tests
# Testing edit_file access
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  # Check package-lock.json for inconsistencies
  package-lock-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Check package-lock.json
        run: |
          if grep -q "localhost" package-lock.json; then
            echo "ERROR: package-lock.json contains localhost references"
            exit 1
          fi

  ubuntu-basic-tests:
    needs: package-lock-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli
      - name: Compile and test
        env:
          # Standard vscode-extension-tester environment variables
          TEST_RESOURCES: test-resources-${{ github.run_id }}
          EXTENSIONS_FOLDER: extensions-${{ github.run_id }}
          CODE_VERSION: 'latest'
          # Custom project variables
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_E2E }}
          DEV_HUB_USER_NAME: ${{ secrets.DEV_HUB_USER_NAME_E2E }}
        run: |
          npm run compile
          mkdir -p $TEST_RESOURCES
          mkdir -p $EXTENSIONS_FOLDER
          npm test

  windows-basic-tests:
    needs: ubuntu-basic-tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli
      - name: Compile and test
        env:
          # Standard vscode-extension-tester environment variables (use forward slashes even on Windows)
          TEST_RESOURCES: test-resources-${{ github.run_id }}
          EXTENSIONS_FOLDER: extensions-${{ github.run_id }}
          CODE_VERSION: 'latest'
          # Custom project variables
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_E2E }}
          DEV_HUB_USER_NAME: ${{ secrets.DEV_HUB_USER_NAME_E2E }}
        run: |
          npm run compile
          New-Item -Path $TEST_RESOURCES -Force -ItemType Directory
          New-Item -Path $EXTENSIONS_FOLDER -Force -ItemType Directory
          npm test
